name: Dotnet nuget push with apikey in cli

# on:
#   push:
#   pull_request:
  
# on: [push]
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --prune --unshallow
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.200
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Pack 
      run: dotnet pack --no-build -c Release erdemDevice/erdemDevice.csproj
    
    # Password encryption is not supported in MAC, Linux.
    - name: Add private GitHub registry to NuGet
      run: dotnet nuget add source https://nuget.pkg.github.com/erdembayar/index.json -n GPR # -u erdembayar -p ${{ secrets.PUSH_TOKEN }} --store-password-in-clear-text
      
    - name: Push generated package to GitHub registry
      run: |
        for f in erdemDevice/bin/Release/*.nupkg
        do
          dotnet nuget push $f --source "GPR" --skip-duplicate --api-key ${{ secrets.PUSH_TOKEN }} #--skip-duplicate
        done
        
        for f in erdemDevice/bin/Release/*.snupkg
        do
          dotnet nuget push $f --source "GPR" --skip-duplicate --api-key ${{ secrets.PUSH_TOKEN }} #--skip-duplicate
        done
      shell: bash
