name: Dotnet push

on: [push]
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    env:
      Solution_Path: erdemDevice.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.0.1
      id: setup_msbuild
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    # Restore the application
    - name:  Restore the application to populate the obj folder
      run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: Debug
        # RuntimeIdentifier: win-${{ matrix.targetplatform }}

    # # - name: Install dependencies
    # #   run: dotnet restore
    # - name: Install dependencies
    #   run: msbuild /t:Restore
    #   env:
    #     NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Run MSBuild
      id: run_msbuild
      # working-directory: $
      # run: msbuild .\erdemDevice.sln /p:Configuration=$env:Configuration
      run: msbuild $env:Solution_Path /p:Configuration=$env:Configuration
      env:
        Configuration: Debug

    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.200
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Pack
      run: msbuild /t:Pack /p:Configuration=Debug erdemDevice/erdemDevice.csproj

    - name: PushNuget
      run: dotnet nuget push bin/Debug/**/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TO_NUGET_ORG }} --skip-duplicate
      
    - name: PushGithub
      run: dotnet nuget push bin/Debug/**/*.nupkg --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}