name: GPR push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --prune --unshallow
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.200
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Pack 
      run: dotnet pack --no-build -c Release erdemDevice/erdemDevice.csproj
    
    - name: Add private GitHub registry to NuGet
      run: dotnet nuget add source https://nuget.pkg.github.com/erdembayar/index.json -n GPR -u erdembayar -p ${{ secrets.PUSH_TOKEN }} #--store-password-in-clear-text
      
    - name: Install tool for working with the GPR
      run: dotnet tool install -g gpr
        
    - name: Push generated package to GitHub registry
      run: |
        for f in erdemDevice/bin/Release/*.nupkg
        do
          gpr push $f -k ${{secrets.PUSH_TOKEN}}
        done
        
        for f in erdemDevice/bin/Release/*.snupkg
        do
          gpr push $f -k ${{secrets.PUSH_TOKEN}}
        done
        
#       powershell
#       $file = Get-ChildItem -Path <where I output my nupkg file to> -Recurse -Filter *.nupkg | Select -First 1
#       gpr push $file.FullName -k ${{secrets.GITHUB_TOKEN}}        
      shell: bash
