name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build_release1:
    env:
        APPVER: 0.11.1
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack 
      run: dotnet pack --no-build -c Release erdemDevice/erdemDevice.csproj      
    - name: version
      run: echo "${APPVER}"
      id: version      
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${APPVER}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
        asset_name: azblogfilter.linux-amd64.tar.gz
        asset_content_type: application/gzip
    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: erdemDevice/bin/Release/erdemDevice*.nupkg
        asset_name: erdemDevice.${APPVER}.gz
        asset_content_type: application/gzip
