name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    PUBLICENV: 2.22.2

jobs:
  build_release1:
    env:
        APPLVER: 0.11.2
        APPVER: 0.13.2
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack 
      run: dotnet pack --no-build -c Release erdemDevice/erdemDevice.csproj
    - name: test1
      run: echo "${APPLVER}"
    - name: test2
      run: echo ${APPLVER}    
    - name: test3
      run: echo ${PUBLICENV}        
    - name: version
      run: echo "${APPVER}"
      id: version
    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::green'
      id: random-color-generator
    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
    - name: GetReleaseVersion
      run: echo "erdemDevice${PUBLICENV}.nupkg"
      id: get-release-version    
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ PUBLICENV }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: erdemDevice/bin/Release/erdemDevice.1.0.0.nupkg
        asset_name: ${{ steps.get-release-version }}"
        asset_content_type: application/gzip
